export const DEFAULT_PAIRS = [
  "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "ADAUSDT", "DOGEUSDT",
  "AVAXUSDT", "LINKUSDT", "DOTUSDT", "LTCUSDT", "TRXUSDT", "MATICUSDT", "ATOMUSDT",
  "NEARUSDT", "APTUSDT", "ARBUSDT", "OPUSDT", "SUIUSDT", "INJUSDT", "FILUSDT",
  "AAVEUSDT", "RUNEUSDT", "PEPEUSDT", "UNIUSDT", "ETCUSDT", "ICPUSDT", "ALGOUSDT"
];
